### ISSUE TITLE
Where can I find the encoders because I do not see them

### ISSUE THREAD

**Issue by LUIDWIGI** [Xaymar/obs-ffmpeg-encoder#1]
### System Information

- Software Version: [23.2.1]
- Operating System: [Windows 10]
- Kernel Version: [1903/1809 (Windows)]
- CPU: [Ryzen 7 3700x]
- GPU: [Nvidia RTX 2070 non super]
- RAM: [16GB 3000MHz cl16]

### Checklist:

- [ ] I have read the contribution guidelines. X
- [ ] This is not a bug, crash or generic issue. X

**Comment by Xaymar** [comment]
The plugin starting from 0.2.0pre2 requires a partially manually built OBS v24. There are builds compatible with v24.0 being worked on, but they are unlikely to be released before v24 is marked stable.
