### ISSUE TITLE
How to select or specify an different GPU to use

### ISSUE THREAD

**Issue by kryztoval** [Xaymar/obs-ffmpeg-encoder#12]
### Description
In a multi-gpu system, how do you tell obs-ffmpeg-encoder which gpu to use?

I have tried "gpu=1", "-gpu 1" and "gpu 1" in the "FFmpeg Options, Custom settings" but I can't make it use the main gpu.

**Comment by Xaymar** [comment]
There is no code currently in place to select other GPUs, and I do not plan to add any code for it. Multi-GPU systems are basically hell to support.

The default GPU it uses should be the one that OBS is also using. If you have Windows 10 you can use the Windows 10 menu to specify the GPU obs64.exe should be using.

**Comment by kryztoval** [comment]
Ok, so let me change the question, 

Is there a parameter that can be passed to ffmpeg to select the gpu. is this exposed in the  "FFmpeg Options, Custom settings" ? if it is what is the format

If it is not exposed then I am sorry I misunderstood. this is currently possible in the "custom output (ffmpeg)" by using the "video encoder settings (if any)" I thought the ffmpeg options were the same but in a different format.  

Thanks for your answer :)

**Comment by Xaymar** [comment]
If there is, it probably relies on the change necessary to fix #5.

**Comment by kryztoval** [comment]
Thanks, I will take a look and report back. I will leave this open while i investigate.

**Comment by Xaymar** [comment]
v0.4 now has improved custom setting parsing in the format of an FFmpeg command line: `-key=value -key2=value2 -key3="quoted value"`.

**Comment by kryztoval** [comment]
I compiled version v0.4 and tested it, it still ignores the gpu directive in any way, shape or form.

I checked the _context->priv_data and it does have the gpu value set in there, I added some code so it would let me know if it can set the values property or if there was an error when setting it up, and it is really useful when trying to set parameters that do not exist.

However the encoder is ignoring the gpu value that is set in the context for some reason. I know that the version implemented by OBS uses the same library and it uses instead the av_opt_set_int to set "gpu" to 0 but I tried doing that directly and that change was still ignored by the encoder.

I wish I could understand what the obs plugin is doing with so many things inside the same object, because it creates a context in the encoder, but the way it creates the encoder is different from how you do both do it and I get lost. Maybe it is the order?

I'm still digging.

**Comment by kryztoval** [comment]
There must be an initialization difference between this and the default OBS ffmpeg plug in, but I can't find it yet.

**Comment by Xaymar** [comment]
Are you using the non `(Software)` encoders? The Hardware encoder **must run on the same GPU OBS is on**, though the code there is going to be refactored to just hijack the OBS created contexts in the near future.

**Comment by kryztoval** [comment]
Oh, so this is the real difference in the way the Custom FFmpeg and the Nvenc are coded for OBS and your plugin. the OBS ones do not reuse the D3D11 context and as such can be sent to any available GPU

**Comment by Xaymar** [comment]
No, that is incorrect. Only the ones not marked with `(Software)` are forced to use the GPU that OBS is running on. The ones with `(Software)` do not have such a restriction. The restriction is also in place for the OBS included `NVIDIA NVENC H.264 (new)` encoder, which is also a full hardware encoder.

**Comment by kryztoval** [comment]
No, you are incorrect.

The NVIDIA NVENC H.264 (new) can and will set the video encode to the GPU that is not being used by OBS nor the DISPLAY if you tell it to.  I know this for a fact since that is EXACTLY the behaviour I am trying to replicate and this is not an issue with that pluging.

And it is indeed a pure hardware encoder.
![image](https://user-images.githubusercontent.com/5733028/68429214-4ba20e80-0173-11ea-9937-f1c90f7274b4.png)

**Comment by Xaymar** [comment]
[If you've actually read the source code for the "NVIDIA NVENC H.264 (new)" encoder, you'd know that setting the GPU field to anything but 0 makes it fall back to the software path again.](https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/jim-nvenc.c#L577)

So, no, I am not incorrect. This is a limitation that is by design because sharing textures across GPUs is dreadfully slow to the point of costing 20-30% of GPU time just for the copy - especially if it needs to be live for encoding.

**Comment by Xaymar** [comment]
I've also pushed a change to v0.4 that now forces a shared D3D11 context with OBS for full hardware encoding so that mixed-GPU systems now work as expected and create the encoder on the same GPU OBS is on. This also further reduces CPU load as the Nvidia driver doesn't spawn extra threads.

**Comment by kryztoval** [comment]
I read the code, and it says it is not gonna do it, but I shown you the GPU is being used with the encoding context in the 2nd gpu while only the first one has 3D on it.

So you can either trust the comment in the source code for the ffmpeg encoder, or trust the hardware. So yeah, your assesment is incorrect.

**Comment by Xaymar** [comment]
"Software", or as I call them "pseudo hardware encoder", in this way means that it uses the following route: GPU -> CPU/RAM -> GPU. This has a huge impact on performance, requiring you to limit the games primary GPU usage to be lower than some unknown % value. "Hardware", or actual "full hardware encoder", do not leave the GPU and can work with as little as 1% gpu time, even less when OBS is run in admin mode.

So while NVENC is "Hardware", not all implementations use the hardware-only path that results in peak performance. Instead they have a similar impact to x264 with their frame download and upload, so they are comparable to "Software", and people understand "Software" better than "(new)".

**Comment by Xaymar** [comment]
Also the Windows Task Manager is notoriously bad at tracking GPU usage to the point of giving a cmd.exe with nothing running it it Video Encode usage. It does its best, but it doesn't track all usage and sometimes even assigns the usage to the wrong GPU.

**Comment by kryztoval** [comment]
Oh, so from what you are saying I understand that if I use the "Software" encoders in your plug in it will actually honor the -gpu=1 flag in the ffmpeg options? I just tested it and you are 100% correct, it does honor it and it encodes in the second GPU. Amazing, this is all I needed. This means my answer to this comment in the very early day was "Use the one that 'says' software, it uses a different path and will encode in the secondary gpu" 

Regarding your second comment about it being more effective, maybe it would be if the encoding route were GPU1 -> CPU/RAM -> GPU1, because in this case it is crossing boundaries to end at the same spot. But in my case this is GPU1 -> CPU/RAM -> GPU2, and in this case, believe it or not (even when nVidia claims it doesn't alter the GPU performance) running the encoder eats away a few FPS in the game.

While I 100% agree using the "Software" version of your encoder makes no sense when using the encoder in the same GPU, I believe that using it in to go to a second GPU makes perfect sense.

And I agree, task manager does the rendering thing, but in my cause the second gpu was at 0% on all accounts until I ran your "software" encoder or the "new" encoder in obs, so I am sure it is being used exclusively by this program, Also, the details tab shows what GPU each process is running, and GPU2 only showed in obs.

**Comment by Xaymar** [comment]
> ... GPU1 -> CPU/RAM -> GPU1 ... GPU1 -> CPU/RAM -> GPU2

Yeah, that is correct. The impact for the "Software" GPU1->GPU1 path is 2.5 times as high as the impact for GPU1->GPU2, mainly due to the necessary synchronization (it's easier to sync two devices than the same device). This won't change until we get D3D12 in OBS and can use multi-device transfer to deal with it and have hardware encoders usable on any NVLINK connected device.

**Comment by kryztoval** [comment]
I created a pull request, it is not needed but sure makes it easier to set up. 😄 

Thanks for the troubleshooting and information.
