### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by kryztoval** [Xaymar/obs-ffmpeg-encoder#18]
I was wondering, would it be possible to add profiles to the plug in?

I know my settings for 1070, 1080, and 1660. but I woudl love if there was a drop down that allowed me to save this in a fiel and apply it back. 

My question is, is this something that is supported by obs? Could I or someone else code it in to the plug in?

Or maybe a small text input that sets all settings based on the string That was added? like a save point for old games.

Just wondering bouncing an idea.

**Comment by Xaymar** [comment]
> My question is, is this something that is supported by obs?

OBS supports profiles which allow you set things per profile. 

> Or maybe a small text input that sets all settings based on the string That was added?

The custom settings field technically allows for this.

**Comment by kryztoval** [comment]
> OBS supports profiles which allow you set things per profile.

I will look into this



> The custom settings field technically allows for this.

Yeah but it doesn't allow you to do quick changes to the settings nor does it allow you to see it represented physically, I meant like a string of chars I could paste into a box and it would set every setting, slider, and checkbox to the correct value from the string pasted. Kind of a way to share the settings, or saving those settings.

**Comment by Xaymar** [comment]
All the sliders, dropdowns etc do is set the things that can be set via custom settings anyway. The Custom Settings have higher priority, so they override anything set above them. There were plans for an import/export function, but that was scrapped as it is way too much work - either deal with the Custom Settings, or use the OBS provided profiles for presets.
