### ISSUE TITLE
FFmpeg Encoders for OBS Studio does not work as it should

### ISSUE THREAD

**Issue by LiaNdrY** [Xaymar/obs-ffmpeg-encoder#4]
### Description
While using OBS with FFmpeg Encoders for OBS Studio 0.3.0pre6 plug-in, enabling Spatial Adaptive Quantization seems to have no effect. Potentially, Temporal AQ does not work as well.

FFmpeg Encoders for OBS Studio 0.3.0pre6
0 value - http://ipic.su/img/img7/fs/1_FFmpegEncodersforOBS_0.1571437182.png
15 value - http://ipic.su/img/img7/fs/1_FFmpegEncodersforOBS_15.1571437212.png

FFmpeg.exe
0 value - http://ipic.su/img/img7/fs/2_ffmpeg_0.1571437333.png
15 value - http://ipic.su/img/img7/fs/2_ffmpeg_15.1571437346.png

Also, the wrong color modes are used, you can not select a limited or full color range, it is always full.

### Expected Behavior
Adaptive Quantization is expected to work.

### Reproduction Steps

1. Start encoding 
2. Make screenshots with and without Spatial AQ (see attached screenshots)
3. They are identical (even if Spatial AQ should be clearly visible during comparison)

### System Information

- Software Version: 0.3.0pre6
- Operating System: Windows 10
- Kernel Version: 1909 18363.418
- CPU: AMD Zen2 3900X
- GPU: Nvidia GTX 1080Ti Series (MSI GamingX)
- RAM: 32GB

### Checklist:

- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
Please attach log files for the issue.

**Comment by Xaymar** [comment]
Aside from the color range, the two example look identical. Color range should be tied to the OBS color range, but it is possible that there is a bug there.

**Comment by LiaNdrY** [comment]
AQ Off - https://pastebin.com/bHAdMC8g
AQ On - https://pastebin.com/aSDHcH0D

**Comment by Xaymar** [comment]
```
01:39:32.810: video settings reset:
01:39:32.810:   base resolution:   2560x1440
01:39:32.810:   output resolution: 1600x900
01:39:32.810:   downscale filter:  Lanczos
01:39:32.810:   fps:               60/1
01:39:32.810:   format:            NV12
01:39:32.810:   YUV mode:          601/Partial
...
01:40:14.232: [obs-ffmpeg-encoder] [h264_nvenc]   Video Input: 1600x900 nv12 BT.601 625 Partial
01:40:14.232: [obs-ffmpeg-encoder] [h264_nvenc]   Video Output: 1600x900 nv12 BT.601 625 Partial
```

OBS Studio is set to partial range, and the plugin correctly detected that and used that for encoding. How did you extract those frames from the encoded video file?

**Comment by LiaNdrY** [comment]
I took a screenshot through the video player.

**Comment by Xaymar** [comment]
Please make sure that your video player supports proper upscaling from the format your are recording to. VLC for example does not support it for all container formats.

Aside from that, `aq-strength` is being correctly passed to nvenc.

**Comment by LiaNdrY** [comment]
I use PotPlayer, but what does it have to do with scaling when I just play a recorded video file.

If aq-strength worked correctly, the picture would not consist of hundreds of small squares.

**Comment by LiaNdrY** [comment]
Here is this plugin works as need to. Even the load increases when encoding via aq-strength 15.
https://obsproject.com/forum/threads/nvenc-adaptive-quantization.65343/#post-282632
https://www.dropbox.com/s/s3343dbm0b11eqm/obs-ffmpeg.rar?dl=0

**Comment by Xaymar** [comment]
Upscaling, or rather Color Conversion, is necessary to play back partial range footage without making color muted. Since partial range is a limited color range which only allows values between 16 and 235, when we fix your image from PotPlayer to be full RGB, it suddenly looks almost identical. So let's compare the two when they are fixed: https://imgsli.com/NzQ5OA

Both sides have visible blocking, despite having the same settings. The blocking just moved to somewhere else.

**Comment by Xaymar** [comment]
If you don't believe me that aq-strength is being correctly set (it should have zero impact on CPU load), you can set all the settings that you used for nvenc_h264 in ffmpeg using the custom settings field. That's what it's there for, to almost 1:1 apply ffmpeg settings.

**Comment by Xaymar** [comment]
MediaInfo reports this for limited/partial range footage:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 21 s 434 ms
Bit rate mode                            : Variable
Maximum bit rate                         : 6 000 kb/s
Width                                    : 1 600 pixels
Height                                   : 900 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.601
Matrix coefficients                      : BT.470 System B/G
```

With this info, any player worth its weight should be able to correctly convert back to full range. And MediaInfo reports this for a full range file:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 27 s 100 ms
Bit rate mode                            : Variable
Maximum bit rate                         : 6 000 kb/s
Width                                    : 1 600 pixels
Height                                   : 900 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Default                                  : Yes
Forced                                   : No
Color range                              : Full
Color primaries                          : BT.601 PAL
Transfer characteristics                 : BT.601
Matrix coefficients                      : BT.470 System B/G
```

Everything is being set correctly from what it looks like.

**Comment by Xaymar** [comment]
I have been unable to reproduce this using your exact configuration. Windows's Movies & TV, VLC, MPC-HC, and even my TV are all playing back Partial footage and Full range footage correctly.

**Comment by LiaNdrY** [comment]
I figured out the color rendering in PotPlayer, it crashes due to adding a parameter in the video " Matrix coefficients: BT.470 System B/G", without it works fine.

Also In the OBS, the partial and full color ranges are interchanged: (It should be the other way around)
https://imgsli.com/NzUwNw

Here are screenshots with normal color rendering of the plugin in OBS:
https://imgsli.com/NzUwOQ

And here are screenshots with normal color rendering FFmpeg.exe:
https://imgsli.com/NzUxMA

**Question!** Why does the recording via streaming in the OBS, so much pixels the picture?

And recording video in OBS or just using FFmpeg.exe – no?

Spatial adaptive quantization 15 – Tries to remove the pixels in the picture, preserving the original quality, using it through streaming to the OBS, I do not observe this. A value of 0 or 15 does not make any difference. The same eggs, only in profile.

If there is a difference, it is invisible because of the many pixels in the picture. And apparently what creates them, prevents to see adaptive quantization in action.

**Comment by Xaymar** [comment]
Regarding Spatial AQ not doing what you expect it to, it actually is doing exactly what it should. See these two files where the only difference is disabling/enabling Spatial AQ. They look very similar, with minor difference in where blocks appear:

* [Spatial AQ Disabled](https://cdn.xaymar.com/ves/%24bf%244%24rc%24cbr_hq%242p%241%24brm%242%24saq%240%24taq%241%24rcla%2432%24wp%240.mp4)
* [Spatial AQ Enabled](https://cdn.xaymar.com/ves/%24bf%244%24rc%24cbr_hq%242p%241%24brm%242%24saq%241%24taq%241%24rcla%2432%24wp%240.mp4)

In these two files, the one with better quality is actually the one with Spatial AQ disabled, in all measurements (VMAF, SSIM, PSNR). And they both have the same blocking **and** were created using FFmpeg h264_nvenc.

> I figured out the color rendering in PotPlayer, it displayed incorrectly due to the addition of the "Matrix coefficients: BT.470 System B/G" parameter in the video, it works fine without it.

That sounds like a PotPlayer bug, you should probably report it to them. I don't seem to be able to repro this issue in any video player and video editing software on Windows that I own.

**Comment by LiaNdrY** [comment]
https://dropmefile.com/ifTtf

The link contains 2 files recorded via FFmpeg with parameters: (As with **-spatial-aq 1 -aq-strength 15** and without them.)
`ffmpeg -i input.mp4 -c: v h264_nvenc -sws_flags lanczos -s 1600x900 -pix_fmt yuv420p -preset: v slow -profile: v high -rc: v vbr_hq -b: v 6144k -bf 4 -rc-lookahead 32 -level 42 -2pass 1 -spatial-aq 1 -aq-strength 15 -refs 4 -c: a: 0 aac -b: a 128k -y Output.mp4`

If we compare the files frame by frame, it can be seen with the naked eye that SAQ 15 saves more details in the frame, while without it, more blurry details.

**Comment by Xaymar** [comment]
You're very welcome to spend an entire month encoding, comparing and running VMAF, SSIM and other metrics and have your own sample content.

**Comment by LiaNdrY** [comment]
Okay. I propose the following: let's close the ticket until i confirm my new suspicion. My current understanding is that it may be the video recorded with stream settings that is introducing the artifacts (not in every frame, too). Maybe this is what makes SAQ hard to see. Perhaps the stream itself is fine, but I cannot confirm it right now. Thanks!
